# Generated by Django 4.0.4 on 2022-05-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productoffer_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoffer',
            old_name='product_id',
            new_name='product',
        ),
    ]
