# Generated by Django 4.0.4 on 2022-05-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avg_rating',
            field=models.FloatField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
