# Generated by Django 4.0.4 on 2022-05-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avg_rating',
            field=models.FloatField(blank=True, default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
