# Generated by Django 4.0.4 on 2022-05-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_avg_rating_alter_profile_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0.0, max_length=4),
        ),
    ]
